// ═══════════════════════════════════════════════════════
//  CS 3365 SOFTWARE ENGINEERING — EXAM 1 QUESTION BANK
//  Chapters 1, 2, 3, 4
//  Types: single, multi, fill, free
//  Each question has `topics` for reinforcement matching
// ═══════════════════════════════════════════════════════

const QUESTION_BANK = [

  // ╔═══════════════════════════════════════╗
  // ║  PROFESSOR CONFIRMED (always included)║
  // ╚═══════════════════════════════════════╝

  {id:"P1",chapter:1,type:"single",fromProfessor:true,topics:["plan-driven","process-models","waterfall"],question:'In a "Plan-driven" process, how is progress typically measured?',options:["By the number of user stories completed each day.","Against a pre-determined plan of activities and stages.","Based on the customer's satisfaction at the end of each sprint.","Based on the level of pair programming used."],answer:[1],explanation:"In plan-driven processes (like Waterfall), progress is measured against a pre-determined plan with defined activities and stages."},
  {id:"P2",chapter:3,type:"single",fromProfessor:true,topics:["scrum","sprint","agile-practices"],question:'In the Scrum agile method, what is a "Sprint"?',options:["A race between developers to finish their code.","A fixed time period, usually 2-4 weeks, during which a system increment is developed.","A meeting where the Scrum Master reports to the CEO.","The process of moving requirements from the product backlog to the archive.","A specialized tool used for automated testing.","The final release of the software to the customer.","A method for scaling agile to large organizations."],answer:[1],explanation:"A Sprint is a fixed time period (typically 2-4 weeks) during which a potentially shippable system increment is developed."},
  {id:"P3",chapter:1,type:"single",fromProfessor:true,topics:["ethics","professional-responsibility"],question:"Software engineering ethics dictate that engineers should NOT:",options:["Respect the confidentiality of employers or clients.","Misuse their skills to take over or damage others' computers.","Be honest about their level of competence.","Support the professional software development of their colleagues."],answer:[1],explanation:"B is what engineers should NOT do. Misusing skills to damage others' computers is unethical."},
  {id:"P4",chapter:3,type:"multi",fromProfessor:true,topics:["agile-characteristics","agile-principles","documentation"],question:"What are the characteristics of agile development? (Select all that apply)",options:["Detailed documentation.","Mostly focused on coding.","Frequent delivery of new versions.","Implementation starts after the system design has been fully completed.","Minimal documentation.","None of the above."],answer:[1,2,4],explanation:"Agile: focus on coding, frequent delivery, minimal documentation."},
  {id:"P5",chapter:2,type:"single",fromProfessor:true,topics:["prototyping","coping-with-change"],question:"The prototype of the software will be very close to the final software version. Therefore, the prototype should not be discarded.",options:["True","False"],answer:[1],explanation:"False. Prototypes are throw-away — built to explore requirements, not become the final product."},
  {id:"P6",chapter:1,type:"single",fromProfessor:true,topics:["generic-vs-customized","product-types"],question:"There are two types of software products: Generic products and customized products. Which one of the following statements is true about a generic product?",options:["Software that is commissioned for specific customer needs.","Software that is developed to maintain the hardware in a specific factory.","Software made for any customer who wants to buy it.","Banking app made for a specific bank to manage its internal activities (ex: Citi bank)."],answer:[2],explanation:"Generic products (COTS) are sold to any customer on the open market."},
  {id:"P7",chapter:2,type:"multi",fromProfessor:true,topics:["waterfall","waterfall-phases","process-models"],question:"The Waterfall Model presents the software development process in a number of stages. What are the phases of the waterfall model? (Select all that apply)",options:["Requirements analysis and definition","Customer involvement","System and software design","Product increments","Implementation and unit testing","Integration and system testing","Version development","Operation and maintenance"],answer:[0,2,4,5,7],explanation:"Waterfall phases: Requirements → Design → Implementation & unit testing → Integration & system testing → Operation & maintenance."},
  {id:"P8",chapter:1,type:"single",fromProfessor:true,topics:["essential-attributes","maintainability"],question:"Which essential software product attribute ensures the system can be adapted to meet the changing needs of customers?",options:["Dependability","Efficiency","Security","Maintainability","Portability"],answer:[3],explanation:"Maintainability = ability to evolve with changing customer needs."},

  // ╔═══════════════════════════════════════╗
  // ║  CHAPTER 1 — INTRODUCTION             ║
  // ╚═══════════════════════════════════════╝

  {id:"C1-01",chapter:1,type:"single",topics:["se-vs-cs","definitions"],question:"What is the key difference between software engineering and computer science?",options:["Software engineering focuses on theories, while computer science focuses on practical development.","Computer science focuses on theories and fundamentals, while software engineering is concerned with the practicalities of developing useful software.","They are the same discipline with different names.","Computer science only deals with hardware design."],answer:[1],explanation:"CS = theory. SE = practical development and delivery."},
  {id:"C1-02",chapter:1,type:"single",topics:["essential-attributes","dependability"],question:"Which essential attribute means the software should not cause physical or economic damage in the event of system failure?",options:["Maintainability","Acceptability","Dependability and Security","Efficiency"],answer:[2],explanation:"Dependability and security = no damage upon failure."},
  {id:"C1-03",chapter:1,type:"single",topics:["maintenance-costs","evolution"],question:"Which of the following is true about maintenance costs in software engineering?",options:["Maintenance costs are typically less than development costs.","Maintenance costs usually exceed development costs for long-lived systems.","Maintenance is not necessary for well-designed software.","Maintenance only includes fixing bugs."],answer:[1],explanation:"Maintenance typically exceeds development costs for long-lived systems."},
  {id:"C1-04",chapter:1,type:"single",topics:["system-of-systems","definitions"],question:'What is a "system of systems"?',options:["A single monolithic application.","A system built by integrating multiple independently managed systems to create a new system.","A backup system that mirrors the primary system.","A system that only runs on one operating system."],answer:[1],explanation:"System of systems = integrating independently managed systems into a larger system."},
  {id:"C1-05",chapter:1,type:"single",topics:["essential-attributes","acceptability"],question:"Which essential product attribute means the software must be understandable, usable, and compatible with existing systems?",options:["Efficiency","Maintainability","Acceptability","Dependability"],answer:[2],explanation:"Acceptability = understandable, usable, compatible."},
  {id:"C1-06",chapter:1,type:"single",topics:["essential-attributes","efficiency"],question:"Which of the following best describes the 'efficiency' attribute of software?",options:["Software should be easy to modify.","Software should not waste system resources like memory and processor cycles.","Software should be secure from external attacks.","Software should be understandable to users."],answer:[1],explanation:"Efficiency = not wasting system resources."},
  {id:"C1-07",chapter:1,type:"fill",topics:["generic-vs-customized","product-types"],question:"The two types of software products are _______ products and _______ products.",answer:["generic","customized"],acceptableAnswers:[["generic","customized"],["generic","custom"],["generic","bespoke"],["customized","generic"],["custom","generic"],["bespoke","generic"]],explanation:"Generic (open market) and customized (bespoke, commissioned)."},
  {id:"C1-08",chapter:1,type:"fill",topics:["essential-attributes"],question:"The four essential attributes of good software are maintainability, dependability and security, efficiency, and _______.",answer:["acceptability"],acceptableAnswers:[["acceptability"],["acceptable"]],explanation:"The four: Maintainability, Dependability & Security, Efficiency, Acceptability."},
  {id:"C1-09",chapter:1,type:"single",topics:["generic-vs-customized","specification-control"],question:"In a customized software product, who controls the software specification?",options:["The software development organization.","The customer who commissions the software.","The end users.","The government regulatory body."],answer:[1],explanation:"For customized products, the commissioning customer controls the specification."},
  {id:"C1-10",chapter:1,type:"single",topics:["ethics","professional-responsibility"],question:"Which of the following is NOT one of the ACM/IEEE ethical principles for software engineers?",options:["Act in a way that is in the best interests of the public.","Maintain integrity and independence in professional judgment.","Maximize profit for the employing organization at all costs.","Advance the integrity and reputation of the profession."],answer:[2],explanation:"Maximizing profit at all costs is NOT an ethical principle."},
  {id:"C1-11",chapter:1,type:"multi",topics:["se-challenges","definitions"],question:"Which of the following are examples of software engineering challenges? (Select all that apply)",options:["Coping with increasing diversity of systems.","Demands for reduced delivery times.","Developing trustworthy software.","Ensuring all software is written in one programming language."],answer:[0,1,2],explanation:"Key challenges: heterogeneity, delivery speed, trustworthiness."},
  {id:"C1-12",chapter:1,type:"fill",topics:["generic-vs-customized","specification-control"],question:"For a generic product, the organization that develops the software controls the software _______.",answer:["specification"],acceptableAnswers:[["specification"],["spec"],["specifications"]],explanation:"For generic products, the development org controls the specification."},

  // ╔═══════════════════════════════════════╗
  // ║  CHAPTER 2 — SOFTWARE PROCESSES        ║
  // ╚═══════════════════════════════════════╝

  {id:"C2-01",chapter:2,type:"single",topics:["incremental-development","process-models"],question:"Which software process model develops the system as a series of versions (increments), with each version adding functionality?",options:["Waterfall Model","Incremental Development","Reuse-oriented Software Engineering","Formal Methods"],answer:[1],explanation:"Incremental development = series of versions."},
  {id:"C2-02",chapter:2,type:"single",topics:["validation","process-activities"],question:"In the software process, which activity involves checking that the software meets its specification and the customer's actual needs?",options:["Specification","Design and Implementation","Validation","Evolution"],answer:[2],explanation:"Validation (V&V) checks conformance to spec and customer needs."},
  {id:"C2-03",chapter:2,type:"multi",topics:["process-activities"],question:"Which of the following are general process activities common to all software processes? (Select all that apply)",options:["Specification","Design and implementation","Pair programming","Validation","Evolution","Daily standups"],answer:[0,1,3,4],explanation:"Four fundamentals: Specification, Design/Implementation, Validation, Evolution."},
  {id:"C2-04",chapter:2,type:"single",topics:["incremental-development","coping-with-change"],question:"What is the primary advantage of incremental development over the waterfall model?",options:["It requires more detailed documentation.","It is easier to accommodate changing customer requirements.","It requires no testing.","It eliminates the need for requirements gathering."],answer:[1],explanation:"Easier to accommodate change via customer feedback on each increment."},
  {id:"C2-05",chapter:2,type:"single",topics:["testing","component-testing"],question:"Which testing stage focuses on testing individual components in isolation?",options:["System testing","Acceptance testing","Component (unit) testing","Integration testing"],answer:[2],explanation:"Component (unit) testing = individual components in isolation."},
  {id:"C2-06",chapter:2,type:"single",topics:["integration-configuration","cots","reuse"],question:"In the Integration and Configuration model, what are COTS systems?",options:["Custom-designed systems built from scratch.","Commercial Off-The-Shelf systems that can be adapted and integrated.","Testing frameworks for component testing.","Coding standards enforced by the team."],answer:[1],explanation:"COTS = Commercial Off-The-Shelf systems."},
  {id:"C2-07",chapter:2,type:"single",topics:["prototyping","coping-with-change"],question:"What is the main purpose of prototyping in software development?",options:["To create the final production version.","To help with requirements elicitation and validation by providing a working model.","To replace the need for testing.","To generate detailed documentation."],answer:[1],explanation:"Prototyping helps elicit and validate requirements."},
  {id:"C2-08",chapter:2,type:"single",topics:["testing","acceptance-testing"],question:"In customer (acceptance) testing, who primarily performs the testing?",options:["The development team.","An automated testing framework.","The customer or end users to validate the system meets their needs.","The project manager."],answer:[2],explanation:"Acceptance testing = customer/end users validate their needs are met."},
  {id:"C2-09",chapter:2,type:"fill",topics:["testing","testing-stages"],question:"The three testing stages in order are: Component testing, _______ testing, and Customer (Acceptance) testing.",answer:["system"],acceptableAnswers:[["system"],["systems"]],explanation:"Component → System → Acceptance."},
  {id:"C2-10",chapter:2,type:"single",topics:["waterfall","process-models"],question:"Which of the following is a key disadvantage of the waterfall model?",options:["It provides too much flexibility.","It produces too little documentation.","Difficulty accommodating change after the process has started.","It delivers software too quickly."],answer:[2],explanation:"Waterfall is inflexible to change once a stage is completed."},
  {id:"C2-11",chapter:2,type:"multi",topics:["coping-with-change","prototyping","incremental-development"],question:"Which are strategies for coping with change? (Select all that apply)",options:["Prototyping","Incremental delivery","Ignoring change requests","Freezing requirements permanently"],answer:[0,1],explanation:"Prototyping and incremental delivery are key change strategies."},
  {id:"C2-12",chapter:2,type:"fill",topics:["evolution","process-activities"],question:"Software _______ is the process of changing a system after it has been delivered.",answer:["evolution"],acceptableAnswers:[["evolution"],["maintenance"]],explanation:"Software evolution = post-delivery changes."},
  {id:"C2-13",chapter:2,type:"single",topics:["waterfall","process-models"],question:"In the waterfall model, when does the customer typically first see a working version?",options:["After the requirements phase.","During the design phase.","Very late, often not until the system is nearly complete.","Before any development begins."],answer:[2],explanation:"Major waterfall drawback: customer sees working system very late."},
  {id:"C2-14",chapter:2,type:"single",topics:["waterfall","process-models"],question:"Which process model is most appropriate when requirements are well-understood and unlikely to change?",options:["Agile development","Waterfall model","Extreme Programming","Scrum"],answer:[1],explanation:"Waterfall works best with stable, well-understood requirements."},
  {id:"C2-15",chapter:2,type:"single",topics:["incremental-development","incremental-delivery"],question:"What is 'incremental delivery'?",options:["Delivering the entire system at once.","Delivering the system in increments, each providing part of the functionality.","Delivering only documentation.","Delivering software only to testers."],answer:[1],explanation:"Incremental delivery = deploy each increment for real use."},

  // ╔═══════════════════════════════════════╗
  // ║  CHAPTER 3 — AGILE DEVELOPMENT         ║
  // ╚═══════════════════════════════════════╝

  {id:"C3-01",chapter:3,type:"single",topics:["agile-manifesto","agile-principles"],question:"According to the Agile Manifesto, which of the following is valued MORE?",options:["Processes and tools over individuals and interactions.","Comprehensive documentation over working software.","Customer collaboration over contract negotiation.","Following a plan over responding to change."],answer:[2],explanation:"Customer collaboration over contract negotiation."},
  {id:"C3-02",chapter:3,type:"single",topics:["xp","refactoring"],question:"In XP, what is improving existing code without changing its external behavior called?",options:["Pair programming","Refactoring","Test-first development","Continuous integration"],answer:[1],explanation:"Refactoring = restructure code, keep behavior the same."},
  {id:"C3-03",chapter:3,type:"single",topics:["xp","test-first","tdd"],question:"What is 'test-first development' in XP?",options:["Testing after all code is written.","Writing tests before writing the code that makes them pass.","Having customers write all tests.","Testing only the UI first."],answer:[1],explanation:"TDD: write tests BEFORE the code."},
  {id:"C3-04",chapter:3,type:"single",topics:["xp","collective-ownership"],question:"What does 'collective ownership' mean in XP?",options:["The project manager owns all code.","All developers share responsibility for all code, anyone can change anything.","Each developer owns specific modules.","The customer owns the source code."],answer:[1],explanation:"Collective ownership = shared responsibility, anyone changes anything."},
  {id:"C3-05",chapter:3,type:"single",topics:["scrum","product-backlog"],question:"In Scrum, what is the Product Backlog?",options:["A list of bugs.","A prioritized list of features, enhancements, and fixes.","The final release documentation.","A record of past sprints."],answer:[1],explanation:"Product Backlog = prioritized work to-do list."},
  {id:"C3-06",chapter:3,type:"single",topics:["scrum","daily-scrum"],question:"What is the purpose of the Daily Scrum?",options:["Assign blame for bugs.","Brief synchronization: what I did, what I'll do, blockers.","Write design documents.","Demo to customers."],answer:[1],explanation:"Daily Scrum = ~15 min sync meeting."},
  {id:"C3-07",chapter:3,type:"single",topics:["xp","user-stories"],question:"In XP, what are 'user stories'?",options:["Detailed UML diagrams.","Short descriptions of functionality from the user's perspective.","Full requirements specs.","Bug reports from end users."],answer:[1],explanation:"User stories = short feature descriptions from user's perspective."},
  {id:"C3-08",chapter:3,type:"single",topics:["xp","small-releases"],question:"What does 'small releases' mean in XP?",options:["Releasing once a year.","Releasing small, frequent increments for quick value delivery.","Releasing only bug fixes.","Releasing to a small number of customers."],answer:[1],explanation:"Small releases = frequent increments, quick value."},
  {id:"C3-09",chapter:3,type:"fill",topics:["scrum","scrum-roles"],question:"In Scrum, the three main roles are the Product Owner, the Development Team, and the _______.",answer:["scrum master"],acceptableAnswers:[["scrum master"],["scrummaster"],["scrum-master"]],explanation:"Three Scrum roles: Product Owner, Dev Team, Scrum Master."},
  {id:"C3-10",chapter:3,type:"fill",topics:["agile-manifesto","agile-principles"],question:"The Agile Manifesto values working _______ over comprehensive documentation.",answer:["software"],acceptableAnswers:[["software"]],explanation:"Working software over comprehensive documentation."},
  {id:"C3-11",chapter:3,type:"single",topics:["xp","agile-practices"],question:"Which of the following is NOT an XP practice?",options:["Pair programming","Test-first development","Big up-front design","Refactoring"],answer:[2],explanation:"Big up-front design is the opposite of XP."},
  {id:"C3-12",chapter:3,type:"single",topics:["xp","pair-programming"],question:"What is pair programming?",options:["Two programmers on separate features.","Two programmers at one workstation — one writes, one reviews.","A programmer and tester on different machines.","Two managers reviewing the plan."],answer:[1],explanation:"Pair programming: driver writes, navigator reviews, one workstation."},
  {id:"C3-13",chapter:3,type:"multi",topics:["agile-manifesto","agile-principles"],question:"Which are values of the Agile Manifesto? (Select all that apply)",options:["Individuals and interactions over processes and tools.","Working software over comprehensive documentation.","Detailed contracts over customer collaboration.","Responding to change over following a plan."],answer:[0,1,3],explanation:"NOT detailed contracts — it's customer collaboration over contract negotiation."},
  {id:"C3-14",chapter:3,type:"single",topics:["scaling-agile","agile-practices"],question:"What challenge does 'scaling agile' address?",options:["Using agile for solo developers.","Applying agile to large systems by large organizations.","Reducing team size.","Limiting features."],answer:[1],explanation:"Scaling agile = large systems, large organizations."},
  {id:"C3-15",chapter:3,type:"fill",topics:["xp","pair-programming"],question:"In XP, _______ programming involves two developers at one workstation.",answer:["pair"],acceptableAnswers:[["pair"]],explanation:"Pair programming."},
  {id:"C3-16",chapter:3,type:"single",topics:["scrum","sprint","sprint-review"],question:"What happens at the end of each Sprint in Scrum?",options:["Project is cancelled if not complete.","Sprint Review: demonstrate increment to stakeholders, get feedback.","All code is deleted.","Mandatory two-week break."],answer:[1],explanation:"Sprint Review = demo + feedback from stakeholders."},
  {id:"C3-17",chapter:3,type:"single",topics:["agile-manifesto","agile-principles"],question:"Which Agile Manifesto value emphasizes adapting over rigid planning?",options:["Individuals and interactions over processes and tools.","Working software over comprehensive documentation.","Customer collaboration over contract negotiation.","Responding to change over following a plan."],answer:[3],explanation:"Responding to change over following a plan."},

  // ╔═══════════════════════════════════════╗
  // ║  CHAPTER 4 — REQUIREMENTS ENGINEERING  ║
  // ╚═══════════════════════════════════════╝

  {id:"C4-01",chapter:4,type:"single",topics:["functional-vs-nonfunctional","requirements-types"],question:"What is the difference between functional and non-functional requirements?",options:["Functional = constraints; non-functional = what system does.","Functional = what system does; non-functional = constraints and quality attributes.","No difference.","Functional = optional; non-functional = mandatory."],answer:[1],explanation:"Functional = what. Non-functional = constraints/quality."},
  {id:"C4-02",chapter:4,type:"multi",topics:["nonfunctional-categories","requirements-types"],question:"Non-functional requirements can be classified into which categories? (Select all that apply)",options:["Product requirements","Organizational requirements","External requirements","Functional requirements","Aesthetic requirements"],answer:[0,1,2],explanation:"Product, Organizational, External."},
  {id:"C4-03",chapter:4,type:"single",topics:["user-vs-system-requirements","requirements-types"],question:"What is the difference between user requirements and system requirements?",options:["User requirements are natural language for stakeholders; system requirements are detailed technical descriptions.","System requirements are natural language; user requirements are technical.","User requirements are for developers; system requirements for managers.","No meaningful difference."],answer:[0],explanation:"User req = natural language for stakeholders. System req = technical for developers."},
  {id:"C4-04",chapter:4,type:"multi",topics:["elicitation-techniques","requirements-elicitation"],question:"Which are requirements elicitation techniques? (Select all that apply)",options:["Interviews","Ethnography","Scenarios and user stories","Pair programming","Refactoring"],answer:[0,1,2],explanation:"Interviews, ethnography, scenarios/user stories are elicitation techniques."},
  {id:"C4-05",chapter:4,type:"single",topics:["ethnography","elicitation-techniques"],question:"What is ethnography in requirements elicitation?",options:["A formal math technique.","An observational technique: analyst observes how people work to discover implicit requirements.","A type of automated testing.","A project management methodology."],answer:[1],explanation:"Ethnography = observe actual work to discover implicit requirements."},
  {id:"C4-06",chapter:4,type:"multi",topics:["requirements-validation","validation-checks"],question:"Requirements validation checks include which of the following? (Select all that apply)",options:["Validity checks — Do requirements reflect real needs?","Consistency checks — Are there contradictions?","Completeness checks — Are all functions included?","Realism checks — Can requirements be implemented within budget/schedule?","Verifiability checks — Can requirements be tested?"],answer:[0,1,2,3,4],explanation:"All five: validity, consistency, completeness, realism, verifiability."},
  {id:"C4-07",chapter:4,type:"single",topics:["requirements-management"],question:"What is requirements management?",options:["Writing all requirements in one sitting.","Managing changing requirements during RE and development.","Deleting difficult requirements.","Assigning each requirement to a developer."],answer:[1],explanation:"Requirements management = managing change during development."},
  {id:"C4-08",chapter:4,type:"single",topics:["stakeholders","requirements-elicitation"],question:"Who are stakeholders in requirements engineering?",options:["Only the development team.","Only end users.","Anyone affected by the system — users, managers, engineers, domain experts.","Only the PM and client."],answer:[2],explanation:"Stakeholders = anyone affected by the system."},
  {id:"C4-09",chapter:4,type:"single",topics:["natural-language","requirements-specification"],question:"What is the main problem with natural language requirements?",options:["Too expensive.","Inherently ambiguous, leading to misunderstandings.","Only programmers understand them.","Cannot express functional requirements."],answer:[1],explanation:"Natural language = ambiguous, different interpretations."},
  {id:"C4-10",chapter:4,type:"fill",topics:["nonfunctional-categories","requirements-types"],question:"The three types of non-functional requirements are product requirements, organizational requirements, and _______ requirements.",answer:["external"],acceptableAnswers:[["external"]],explanation:"Product, Organizational, External."},
  {id:"C4-11",chapter:4,type:"fill",topics:["requirements-engineering","definitions"],question:"Requirements _______ is the process of discovering, analyzing, documenting, and checking requirements.",answer:["engineering"],acceptableAnswers:[["engineering"],["elicitation"]],explanation:"Requirements engineering."},
  {id:"C4-12",chapter:4,type:"single",topics:["scenarios","elicitation-techniques"],question:"Which elicitation technique involves a narrative description of user-system interaction to accomplish a goal?",options:["Ethnography","Interviews","Scenarios","Brainstorming"],answer:[2],explanation:"Scenarios = narrative descriptions of interactions."},
  {id:"C4-13",chapter:4,type:"single",topics:["nonfunctional-categories","product-requirements"],question:"'The system shall process 99.9% of transactions within 2 seconds' is what type of requirement?",options:["Functional requirement","Non-functional product requirement","Non-functional organizational requirement","Non-functional external requirement"],answer:[1],explanation:"Performance = non-functional product requirement."},
  {id:"C4-14",chapter:4,type:"single",topics:["nonfunctional-categories","external-requirements"],question:"'The system must comply with HIPAA regulations' is what type of requirement?",options:["Functional requirement","Non-functional product requirement","Non-functional organizational requirement","Non-functional external requirement"],answer:[3],explanation:"Regulatory compliance = non-functional external requirement."},
  {id:"C4-15",chapter:4,type:"multi",topics:["requirements-engineering","re-activities"],question:"Which are activities in the requirements engineering process? (Select all that apply)",options:["Requirements elicitation","Requirements specification","Requirements validation","Requirements implementation","Requirements negotiation"],answer:[0,1,2,4],explanation:"Elicitation, specification, validation, negotiation. NOT implementation."},
  {id:"C4-16",chapter:4,type:"fill",topics:["functional-vs-nonfunctional","requirements-types"],question:"_______ requirements define the services the system should provide and how it should behave.",answer:["functional"],acceptableAnswers:[["functional"]],explanation:"Functional requirements = services, behaviors."},

  // ╔═══════════════════════════════════════╗
  // ║  FREE RESPONSE (always included)       ║
  // ╚═══════════════════════════════════════╝

  {id:"FR1",chapter:3,type:"free",topics:["agile-manifesto","agile-principles"],question:"Describe the four core values of the Agile Manifesto. For each value, explain what is valued more and what is valued less, and why this matters for software development.",answer:[],explanation:"(1) Individuals and interactions over processes and tools (2) Working software over comprehensive documentation (3) Customer collaboration over contract negotiation (4) Responding to change over following a plan. Both sides have value; left is valued more."},
  {id:"FR2",chapter:2,type:"free",topics:["waterfall","incremental-development","process-models"],question:"Compare and contrast the Waterfall Model with Incremental Development. Discuss advantages, disadvantages, and when each is most appropriate.",answer:[],explanation:"Waterfall: sequential, good docs, stable requirements, inflexible. Incremental: iterative, adaptable, early feedback, less documentation. Waterfall for safety-critical; Incremental for evolving business needs."},
];

// ╔══════════════════════════════════════════════════════╗
// ║  REINFORCEMENT BANK — Extra questions per topic      ║
// ║  Used ONLY in "Review & Reinforce" mode              ║
// ╚══════════════════════════════════════════════════════╝

const REINFORCEMENT_BANK = [
  // Essential Attributes
  {id:"R-EA-01",chapter:1,type:"single",topics:["essential-attributes","maintainability"],question:"A client says: 'We need new reporting features every quarter as regulations change.' Which essential attribute is MOST important?",options:["Efficiency","Maintainability","Dependability","Acceptability"],answer:[1],explanation:"Frequently changing features = maintainability is key."},
  {id:"R-EA-02",chapter:1,type:"single",topics:["essential-attributes","dependability"],question:"A medical device software failure could endanger patients. Which attribute is TOP priority?",options:["Acceptability","Efficiency","Dependability and Security","Maintainability"],answer:[2],explanation:"Potential physical harm = dependability and security."},
  {id:"R-EA-03",chapter:1,type:"single",topics:["essential-attributes","efficiency"],question:"An embedded system has only 256KB of RAM. Which attribute is most constrained?",options:["Maintainability","Efficiency","Acceptability","Dependability"],answer:[1],explanation:"Severely limited resources = efficiency is critical."},
  {id:"R-EA-04",chapter:1,type:"single",topics:["essential-attributes","acceptability"],question:"Users find a new payroll system confusing and incompatible with their HR tools. Which attribute is lacking?",options:["Dependability","Acceptability","Maintainability","Efficiency"],answer:[1],explanation:"Confusing + incompatible = poor acceptability."},
  {id:"R-EA-05",chapter:1,type:"multi",topics:["essential-attributes"],question:"Which are the four essential attributes of good software? (Select all that apply)",options:["Maintainability","Scalability","Dependability and Security","Efficiency","Acceptability","Portability"],answer:[0,2,3,4],explanation:"The four: Maintainability, Dependability & Security, Efficiency, Acceptability."},

  // Ethics
  {id:"R-ETH-01",chapter:1,type:"single",topics:["ethics","professional-responsibility"],question:"An engineer discovers their employer is shipping software with known security flaws. Per the ACM/IEEE Code, they should prioritize:",options:["Loyalty to employer above all.","The public interest and safety.","Meeting the deadline regardless.","Keeping quiet to avoid conflict."],answer:[1],explanation:"Public interest and safety = highest priority in the code of ethics."},
  {id:"R-ETH-02",chapter:1,type:"single",topics:["ethics","professional-responsibility"],question:"An engineer is asked to work on a project outside their expertise. Per professional ethics, they should:",options:["Accept and figure it out silently.","Be honest about their competence level and seek training or assistance.","Decline all unfamiliar work.","Blame failures on the PM."],answer:[1],explanation:"Be honest about competence; it's OK to learn but you must be transparent."},

  // Generic vs Customized
  {id:"R-GC-01",chapter:1,type:"single",topics:["generic-vs-customized","product-types"],question:"Microsoft Word is an example of which type of software product?",options:["Customized product","Generic product","Open-source product","Embedded product"],answer:[1],explanation:"Sold to anyone on the open market = generic product."},
  {id:"R-GC-02",chapter:1,type:"single",topics:["generic-vs-customized","specification-control"],question:"Who decides features for the next version of a generic product?",options:["Individual customers.","The development organization.","Government regulators.","End users through voting."],answer:[1],explanation:"For generic products, the development organization controls the specification."},

  // Waterfall
  {id:"R-WF-01",chapter:2,type:"single",topics:["waterfall","waterfall-phases"],question:"Which waterfall phase comes immediately after 'System and software design'?",options:["Requirements analysis","Implementation and unit testing","Integration and system testing","Operation and maintenance"],answer:[1],explanation:"Sequence: Requirements → Design → Implementation & unit testing."},
  {id:"R-WF-02",chapter:2,type:"single",topics:["waterfall","process-models","plan-driven"],question:"Why is waterfall called a 'plan-driven' process?",options:["It doesn't require planning.","All activities must be planned and scheduled before development begins.","The customer plans all features.","It uses planning poker."],answer:[1],explanation:"Plan-driven = everything planned and scheduled in advance."},
  {id:"R-WF-03",chapter:2,type:"fill",topics:["waterfall","waterfall-phases"],question:"The first phase of waterfall is requirements analysis and _______.",answer:["definition"],acceptableAnswers:[["definition"]],explanation:"First phase: Requirements Analysis and Definition."},

  // Prototyping
  {id:"R-PROTO-01",chapter:2,type:"single",topics:["prototyping","coping-with-change"],question:"Why should a prototype typically be discarded?",options:["Always written in a different language.","Prototypes sacrifice quality and structure for speed — using them as production code creates technical debt.","Customers don't want them.","It's illegal to keep them."],answer:[1],explanation:"Prototypes cut corners on quality; using them as production code = massive tech debt."},
  {id:"R-PROTO-02",chapter:2,type:"multi",topics:["prototyping","coping-with-change"],question:"What are benefits of prototyping? (Select all that apply)",options:["Clarifies unclear requirements.","Stakeholders see a working model early.","Eliminates the need for validation.","Reveals design problems before full implementation."],answer:[0,1,3],explanation:"Prototyping clarifies requirements, provides early interaction, reveals design issues. Does NOT eliminate validation."},

  // Testing
  {id:"R-TEST-01",chapter:2,type:"single",topics:["testing","testing-stages"],question:"Which testing stage verifies the integrated system meets its specification?",options:["Component testing","System testing","Acceptance testing","Unit testing"],answer:[1],explanation:"System testing = complete integrated system vs. specification."},
  {id:"R-TEST-02",chapter:2,type:"single",topics:["testing","acceptance-testing"],question:"What is the goal of acceptance testing?",options:["Find bugs in individual functions.","Verify the system meets real-world customer needs before deployment.","Test under extreme load.","Ensure all code is commented."],answer:[1],explanation:"Acceptance testing = validate customer's real needs before deployment."},

  // Process Activities
  {id:"R-PA-01",chapter:2,type:"fill",topics:["process-activities"],question:"The four fundamental process activities are specification, design and implementation, validation, and _______.",answer:["evolution"],acceptableAnswers:[["evolution"]],explanation:"Specification, Design/Implementation, Validation, Evolution."},

  // Scrum
  {id:"R-SCR-01",chapter:3,type:"single",topics:["scrum","scrum-roles","product-backlog"],question:"Who manages and prioritizes the Product Backlog in Scrum?",options:["Scrum Master","Product Owner","Development Team","Stakeholders"],answer:[1],explanation:"Product Owner manages the backlog."},
  {id:"R-SCR-02",chapter:3,type:"single",topics:["scrum","scrum-roles"],question:"What is the Scrum Master's primary responsibility?",options:["Writing code.","Managing the budget.","Facilitating the Scrum process and removing impediments.","Making all technical decisions."],answer:[2],explanation:"Scrum Master = facilitator + impediment remover."},
  {id:"R-SCR-03",chapter:3,type:"single",topics:["scrum","sprint","sprint-review"],question:"How does a Sprint Review differ from a Sprint Retrospective?",options:["They are the same meeting.","Review demos to stakeholders; Retrospective is for the team to reflect on process.","Retrospective demos; Review reflects.","Neither involves the dev team."],answer:[1],explanation:"Review = demo for stakeholders. Retrospective = team process reflection."},

  // XP Practices
  {id:"R-XP-01",chapter:3,type:"single",topics:["xp","refactoring"],question:"A developer notices duplicated code in three modules. It works correctly. Per XP, they should:",options:["Leave it since it works.","Refactor to eliminate duplication while keeping behavior the same.","Rewrite all three from scratch.","Add comments explaining the duplication."],answer:[1],explanation:"XP encourages continuous refactoring to keep code clean."},
  {id:"R-XP-02",chapter:3,type:"single",topics:["xp","test-first","tdd"],question:"In TDD, what is the correct sequence?",options:["Write code → Write test → Run test","Write test → Run test (fail) → Write code → Run test (pass)","Write code → Run → Write test if bugs found","Write docs → Write test → Write code"],answer:[1],explanation:"TDD: Write failing test → Write code to pass → Refactor → Repeat."},
  {id:"R-XP-03",chapter:3,type:"multi",topics:["xp","agile-practices"],question:"Which are XP practices? (Select all that apply)",options:["Pair programming","Collective ownership","Big up-front design","Small releases","Test-first development","Comprehensive docs before coding"],answer:[0,1,3,4],explanation:"XP: pair programming, collective ownership, small releases, TDD. NOT big design or comprehensive docs."},

  // Agile Manifesto
  {id:"R-AM-01",chapter:3,type:"fill",topics:["agile-manifesto","agile-principles"],question:"The Agile Manifesto values customer _______ over contract negotiation.",answer:["collaboration"],acceptableAnswers:[["collaboration"]],explanation:"Customer collaboration over contract negotiation."},
  {id:"R-AM-02",chapter:3,type:"fill",topics:["agile-manifesto","agile-principles"],question:"The Agile Manifesto values _______ and interactions over processes and tools.",answer:["individuals"],acceptableAnswers:[["individuals"]],explanation:"Individuals and interactions over processes and tools."},
  {id:"R-AM-03",chapter:3,type:"single",topics:["agile-manifesto","agile-principles"],question:"The Agile Manifesto says 'while there is value in the items on the right, we value the items on the left more.' This means:",options:["Items on the right are worthless.","Both sides have value, but left-side items are prioritized.","Only left-side items should be used.","Right-side items are more important in practice."],answer:[1],explanation:"Both sides have value — left is valued MORE, not exclusively."},

  // Requirements Types
  {id:"R-REQ-01",chapter:4,type:"single",topics:["functional-vs-nonfunctional","requirements-types"],question:"'The system shall allow users to search for flights by date and destination' is:",options:["Non-functional requirement","Functional requirement","Organizational requirement","External requirement"],answer:[1],explanation:"Describes what the system does = functional requirement."},
  {id:"R-REQ-02",chapter:4,type:"single",topics:["functional-vs-nonfunctional","requirements-types"],question:"'The system shall respond to search queries within 3 seconds' is:",options:["Functional requirement","Non-functional product requirement","Non-functional organizational requirement","Non-functional external requirement"],answer:[1],explanation:"Performance constraint = non-functional product requirement."},
  {id:"R-REQ-03",chapter:4,type:"single",topics:["nonfunctional-categories","requirements-types"],question:"'All code must follow company coding standards and be reviewed before merging' is:",options:["Functional requirement","Non-functional product requirement","Non-functional organizational requirement","Non-functional external requirement"],answer:[2],explanation:"Coding standards from the organization = organizational requirement."},

  // Elicitation
  {id:"R-ELIC-01",chapter:4,type:"single",topics:["ethnography","elicitation-techniques"],question:"An analyst spends two weeks with nurses in a hospital to understand their workflow. This is:",options:["Interviewing","Prototyping","Ethnography","Brainstorming"],answer:[2],explanation:"Observing people in their actual work environment = ethnography."},
  {id:"R-ELIC-02",chapter:4,type:"single",topics:["scenarios","elicitation-techniques","user-stories"],question:"How do scenarios differ from user stories?",options:["Scenarios are shorter.","Scenarios provide detailed narratives; user stories are brief, high-level.","User stories are more detailed.","No difference."],answer:[1],explanation:"Scenarios = detailed narratives. User stories = brief ('As a [user], I want [goal]')."},

  // Validation
  {id:"R-VAL-01",chapter:4,type:"single",topics:["requirements-validation","validation-checks"],question:"Two requirements contradict each other. Which validation check caught this?",options:["Validity check","Consistency check","Completeness check","Realism check"],answer:[1],explanation:"Consistency checks find contradictions between requirements."},
  {id:"R-VAL-02",chapter:4,type:"single",topics:["requirements-validation","validation-checks"],question:"A reviewer asks: 'Can we build this within our $50K budget and 3-month timeline?' This is:",options:["Validity check","Consistency check","Verifiability check","Realism check"],answer:[3],explanation:"Budget/timeline feasibility = realism check."},

  // User vs System Requirements
  {id:"R-USR-01",chapter:4,type:"single",topics:["user-vs-system-requirements"],question:"User req: 'Easy for managers to view monthly sales reports.' The system req would be:",options:["An identical copy.","Detailed spec: 'Generate monthly PDF reports, accessible via Reports menu, filtered by date and category.'","Just 'Generate reports.'","A UML diagram only."],answer:[1],explanation:"System requirements translate user needs into detailed technical specifications."},

  // Requirements Management
  {id:"R-RM-01",chapter:4,type:"single",topics:["requirements-management"],question:"Why is requirements management necessary?",options:["Requirements never change.","Requirements inevitably change as understanding grows and business needs evolve.","It creates busywork.","Waterfall requires it but agile does not."],answer:[1],explanation:"Change is inevitable — RM ensures changes are tracked and properly incorporated."},

  // Incremental Development
  {id:"R-INC-01",chapter:2,type:"single",topics:["incremental-development","process-models"],question:"What is a key disadvantage of incremental development for large, long-lived systems?",options:["It's too slow.","Structure degrades over time; documentation may be insufficient for long-term maintenance.","Customers never provide useful feedback.","It can only produce small systems."],answer:[1],explanation:"Incremental development can lead to structural degradation and insufficient documentation."},

  // COTS
  {id:"R-COTS-01",chapter:2,type:"single",topics:["integration-configuration","cots","reuse"],question:"What is the main trade-off when using COTS components?",options:["COTS are always more expensive.","Requirements may need to adapt to available components, compromising ideal design.","COTS cannot be tested.","COTS are always outdated."],answer:[1],explanation:"Using COTS often means adapting requirements to fit available components."},
];

window.QUESTION_BANK = QUESTION_BANK;
window.REINFORCEMENT_BANK = REINFORCEMENT_BANK;
